### ISSUE TITLE
Text-Card Feature

### ISSUE THREAD

**Issue by gkruchin** [team-panda-whale/whos-on-the-ballot#6]

**Comment by jamesscaggs** [comment]
- [x] Add input
- [x] Wire up input onchange handler
- [x] Add button
- [x] Create a sendSMS function with axios to Twilio create SMS API
- [x] Wire up button

**Comment by jamesscaggs** [comment]
- [x] Add API route
- [x] Add Send SMS controller
- [x] Set up Env's for Twilio API
- [x] Handle Input state change

**Comment by jamesscaggs** [comment]
- [x] Make message body dynamic based on selected list
- [x] Add visual feedback
